name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate the snake files in svg
        id: snake
        uses: Platane/snk@v3
        with:
          github_user_name: adamaryanto
          outputs: |
            dist/snake.svg?color_snake=#7c3aed&color_dots=#ebedf0,#9be9a8,#f1c40f,#fb923c,#f87171
            dist/snake-dark.svg?color_snake=#a371f7&color_dots=#161b22,#2ea043,#d29922,#f0883e,#ff7b72

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: snake-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
